CREATE DATABASE IF NOT EXISTS college;
USE college;

CREATE TABLE student (
	ROLLNO INT PRIMARY KEY,
    NAME VARCHAR(50), 
    MARKS INT NOT NULL,
    GRADE VARCHAR(1),
    CITY VARCHAR(20)
);

INSERT INTO student 
	(ROLLNO, NAME, MARKS, GRADE, CITY)
	VALUES
	(101, "ANIL", 78, 'C', "PUNE"),
    (102, "BHUMIKA", 93, 'A', "MUMBAI"),
    (103, "CHETAN", 85, 'B', "MUMBAI"),
    (104, "DHRUV", 96, "A", "DELHI"),
    (105, "ESHANN", 12, "F", "DELHI"),
    (106, "FARHAN", 82, "B", "DELHI")
;

SELECT * FROM student; -- QUERY ALL THE COLUMNS OF THE TABLE

SELECT DISTINCT CITY FROM student; -- QUERY UNIQUE CITY FROM STUDENT TABLE

SELECT NAME, CITY FROM student; -- QUERY ONLY NAME AND CITY COLUMN FROM THE STUDENT TABLE

SELECT * FROM student WHERE MARKS > 80; -- GIVES STUDENT WITH MARKS > 80

SELECT NAME AS "FULL NAME" FROM student WHERE CITY = "MUMBAI"; -- STUDENT WHO LIVE IN MUMBAI

SELECT * FROM student WHERE MARKS > 80 AND CITY = "MUMBAI"; -- AND OPERATOR FOR MULTI CONDITION