USE college;

-- AND LOGICAL OPERATOR  
SELECT * FROM student WHERE MARKS > 80 AND CITY = "MUMBAI";

-- OR LOGICAL OPERATOR 
SELECT * FROM student WHERE MARKS > 80 OR CITY = "INDORE";

-- BETWEEN OPERATOR
SELECT * FROM student WHERE MARKS BETWEEN 85 AND 90; -- RANGES ARE INCLUSIVE
SELECT * FROM student WHERE CITY BETWEEN "DELHI" AND "PUNE";

-- IN OPERATOR
SELECT * FROM student WHERE CITY IN ("DEWAS", "INDORE", "PUNE");

-- NOT OPERATOR
SELECT * FROM student WHERE MARKS NOT BETWEEN 85 AND 100;
