USE college;

-- LIMIT CLAUSE
SELECT * FROM student WHERE MARKS > 70 LIMIT 2;

-- ORDER BY CLAUSE
SELECT NAME, MARKS FROM student ORDER BY MARKS; -- DEFAULT ASCENDING
SELECT NAME, MARKS FROM student ORDER BY MARKS DESC LIMIT 3;