USE college;

-- AGGREGATE FUNCTIONS ARE FUNCTIONS THAT PERFORM A CALCULATION ON A SET
-- OF VALUES AND RETURN A SINGLE VALUE

SELECT sum(MARKS) AS TOTAL_MARKS FROM student;
SELECT count(*) AS TOTAL_STUDENTS FROM student;
SELECT max(MARKS) AS MAXIMUM_MARKS FROM student;
SELECT min(MARKS) AS MINIMUM_MARKS FROM student;
SELECT avg(MARKS) AS AVERAGE_MARKS FROM student;