USE college;

-- GROUP BY GROUPS ROWS THAT HAVE THE SAME VALUES INTO SUMMARY ROWS
-- COLLECTS DATA FROM MULTIPLE RECORDS AND GROPS THE RESULT BY ONE OR TWO COLUMNS
-- GENERALLY, WE USE GROUP BY WITH SOME AGGREGATION FUNCTION

SELECT CITY, count(NAME), sum(MARKS), avg(MARKS) FROM student GROUP BY CITY;
SELECT CITY, avg(MARKS) FROM student GROUP BY CITY ORDER BY avg(MARKS);

SELECT GRADE, COUNT(GRADE) FROM student GROUP BY GRADE ORDER BY COUNT(GRADE);

-- HAVING CLAUSE: USED TO APPLY CONDITIONS TO GROUPS DESPITE NORMAL ROWS
SELECT CITY, COUNT(ROLLNO) FROM student GROUP BY CITY HAVING MAX(MARKS) > 90;