USE college;

-- PARENT TABLE
CREATE TABLE department (
	ID INT PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL
);

INSERT INTO department (ID, NAME) VALUES
	(101, "SCIENCE"),
    (102, "MATHS"),
    (103, "ENGLISH"),
    (104, "HINDI")
;

-- CHILD TABLE
CREATE TABLE teacher (
	ID INT PRIMARY KEY,
    NAME VARCHAR(50),
    DEPT_ID INT, 
    FOREIGN KEY (DEPT_ID) REFERENCES department(ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

INSERT INTO teacher (ID, NAME, DEPT_ID) VALUES
	(101, "AAYUSH", 101),
    (102, "BABLU", 103),
    (103, "SOHAM", 104),
    (104, "FARHAN", 103),
    (105, "ROHAN", 102)
;

SELECT * FROM department;
SELECT * FROM teacher;

-- CHANGING THE ID OF HINDI DEPARTMENT FOR ILLUSTRATING ON UPDATE CASCASE
SET SQL_SAFE_UPDATES = 0;
UPDATE department SET ID = 105 WHERE NAME = "HINDI";

-- DELETING HINDI DEPARTMENT FOR ILLUSTRATING ON DELETE CASCASE
DELETE FROM department WHERE ID=105;
