CREATE DATABASE joins;
USE joins;

CREATE TABLE STUDENT (
	ID INT PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL
);

INSERT INTO STUDENT VALUES
	(101, "AYUSH"),
    (102, "BALRAM"),
    (103, "CHARAN"),
    (104, "DEEPAK")
;

CREATE TABLE COURSE (
	ID INT PRIMARY KEY,
    NAME VARCHAR(50)
);

INSERT INTO COURSE VALUES
	(102, "ENGLISH"),
    (105, "MATHS"),
    (103, "SCIENCE"),
    (107, "COMPUTER SCIENCE")
;

-- INNER JOIN
SELECT *
FROM STUDENT S
INNER JOIN COURSE C
ON S.ID = C.ID;

-- LEFT OUTER JOIN
SELECT S.ID, S.NAME, C.NAME
FROM STUDENT S
LEFT JOIN COURSE C
ON S.ID = C.ID; 

-- RIGHT OUTER JOIN
SELECT S.ID, S.NAME, C.NAME
FROM STUDENT S 
RIGHT JOIN COURSE C
ON S.ID = C.ID;

-- FULL JOIN
SELECT S.ID, S.NAME, C.NAME
FROM STUDENT S
LEFT JOIN COURSE C
ON S.ID = C.ID
UNION
SELECT S.ID, S.NAME, C.NAME
FROM STUDENT S 
RIGHT JOIN COURSE C
ON S.ID = C.ID;

-- LEFT EXCLUSIVE JOIN
SELECT * 
FROM STUDENT S
LEFT JOIN COURSE C
ON S.ID = C.ID
WHERE C.ID IS NULL;

-- RIGHT EXCLUSIVE JOIN
SELECT * 
FROM STUDENT S
RIGHT JOIN COURSE C
ON S.ID = C.ID
WHERE S.ID IS NULL;

-- FULL EXCLUSIVE JOIN

SELECT *
FROM STUDENT S
LEFT JOIN COURSE C
ON S.ID = C.ID
WHERE C.ID IS NULL
UNION
SELECT * FROM STUDENT S
RIGHT JOIN COURSE C
ON S.ID = C.ID
WHERE S.ID IS NULL;