USE college;

-- QUERY TO FIND STUDENTS WITH MARKS GREATER THAN AVERAGE MARKS
SELECT NAME, MARKS
FROM STUDENT
WHERE MARKS > (
	SELECT AVG(MARKS) FROM STUDENT
) ORDER BY MARKS;

-- FINDING THE STUDENTS WITH EVEN ROLL NUMBER
SELECT ROLLNO, NAME 
FROM STUDENT
WHERE ROLLNO IN (
	SELECT ROLLNO FROM STUDENT WHERE ROLLNO % 2 = 0
);

-- SELECT MAX MARKS OF DELHI STUDENT
SELECT MAX(MARKS) 
FROM STUDENT
WHERE CITY = "DELHI";

SELECT MARKS
FROM STUDENT
WHERE CITY = "DELHI" ORDER BY MARKS DESC LIMIT 1; 

-- SUBQUERY USING FROM
SELECT MAX(MARKS)
FROM (
	SELECT MARKS FROM STUDENT WHERE CITY = "DELHI"
) AS TEMP;

