USE college;

-- VIEWS ARE LIKE VIRTUAL TABLES OR PART OF A TABLE. 
-- USED TO PROVIDE ABSTRACTION BETWEEN DIFFERENT LAYERS
-- VIEW ALWAYS SHOW UP-TO-DATE DATA AS EVERY TIME, DATABASE IS UPDATED, VIEW IS UPDATED BY RECREATION.

CREATE VIEW TEACHER_VIEW AS
	SELECT ROLLNO, NAME, MARKS FROM STUDENT;

SELECT * FROM TEACHER_VIEW WHERE MARKS > 90;
DROP VIEW TEACHER_VIEW;